name: IRSRMamba_tgrs_x2_0407
model_type: MambaIRModel
scale: 2
num_gpu: auto
manual_seed: 3407
# dataset and data loader settings
datasets:
  train:
    name: M3FD
    type: PairedImageDataset
    dataroot_gt: /home/usrs/hys/0010_Dataset/M3FD_Fusion_SR/M3FD_Fusion_train/lr/HR
    dataroot_lq: /home/usrs/hys/0010_Dataset/M3FD_Fusion_SR/M3FD_Fusion_train/lr/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk


    gt_size: 32
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

val_1:
    name: results-A
    type: PairedImageDataset
    dataroot_gt: /home/usrs/hys/0010_Dataset/2024_0401_SPL/test/results-A/HR
    dataroot_lq: /home/usrs/hys/0010_Dataset/2024_0401_SPL/test/results-A/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk
      
  val_2:
    name: results-C
    type: PairedImageDataset
    dataroot_gt: /home/usrs/hys/0010_Dataset/2024_0401_SPL/test/results-C/HR
    dataroot_lq: /home/usrs/hys/0010_Dataset/2024_0401_SPL/test/results-C/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

  val_3:
    name: CVC10
    type: PairedImageDataset
    dataroot_gt: /home/usrs/hys/0010_Dataset/2024_0401_SPL/test/CVC10/CVC15_HR
    dataroot_lq: /home/usrs/hys/0010_Dataset/2024_0401_SPL/test/CVC10/CVC15_LR/X2
    filename_tmpl: '{}'
    io_backend:
      type: disk
      

# network structures
network_g:
  type: IRSRMamba
  upscale: 2
  in_chans: 3
  img_size: 64
  img_range: 1.
  d_state: 16
  depths: [8, 8, 8, 8, 8, 8]
  embed_dim: 180
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    #lr: !!float 2e-4
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [5000, 10000, 15000, 20000, 25000, 30000, 35000]
    #milestones: [5000, 10000, 15000, 20000，25000，30000，35000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  # pixel_opt:
  #   type: SSM_L1Loss           
  #   weights: [1.0]             
  #   lambda_weight: 1.0         
  #   reduction: mean            
  #   aggregate_fn: mean  

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      better: higher
      test_y_channel: true

    mse: # metric name, can be arbitrary
      type: calculate_mse
      crop_border: 2
      better: lower
      test_y_channel: true

    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true

    niqe:
      type: calculate_niqe
      crop_border: 2
      better: lower  # the lower, the better




# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
